#!/bin/bash


# Append config required by aws related plugins to wp-config-sample.php
cat >> $WWW_ROOT/wp-config-sample.php <<-EOCONFIG

/** AWS settings */
define('AWS_ACCESS_KEY_ID', 'aws access key here' );
define('AWS_SECRET_ACCESS_KEY', 'aws secret here' );
EOCONFIG

# Replace runtime variables into config files
sed -e "s/database_name_here/$MYSQL_DATABASE_NAME/
  s/username_here/$MYSQL_USER/
  s/password_here/$MYSQL_PASSWORD/
  /'DB_HOST'/s/localhost/$MYSQL_PORT_3306_TCP_ADDR/
  /'AWS_ACCESS_KEY_ID'/s/aws access key here/$AWS_ACCESS_KEY/
  /'AWS_SECRET_ACCESS_KEY'/s/aws secret here/$AWS_SECRET_KEY/
  /'AUTH_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'SECURE_AUTH_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'LOGGED_IN_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'NONCE_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'AUTH_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'SECURE_AUTH_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'LOGGED_IN_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
  /'NONCE_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/" $WWW_ROOT/wp-config-sample.php > $WWW_ROOT/wp-config.php


# Turn on debug if switch is on
if [ $DEBUG = "yes" ]; then
  sed -e "/'WP_DEBUG'/s/false/true/" $WWW_ROOT/wp-config.php > $WWW_ROOT/wp-config-debug.php
  mv $WWW_ROOT/wp-config-debug.php $WWW_ROOT/wp-config.php
fi

chown www-data:www-data $WWW_ROOT/wp-config.php


# Create user access
HOST_IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | head -n 1`
tempSqlFile='/tmp/mysql-first-time.sql'
cat > "$tempSqlFile" <<-EOSQL
  CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE_NAME}\`;
  CREATE USER '$MYSQL_USER'@'$HOST_IP' IDENTIFIED BY '$MYSQL_PASSWORD';
  GRANT ALL ON \`${MYSQL_DATABASE_NAME}\`.* TO '$MYSQL_USER'@'$HOST_IP';
  FLUSH PRIVILEGES;
EOSQL

mysql -h $MYSQL_PORT_3306_TCP_ADDR -P $MYSQL_PORT_3306_TCP_PORT -u$MYSQL_ROOT_USER -p$MYSQL_ROOT_PASSWORD < $tempSqlFile
rm $tempSqlFile
MYSQL_ROOT_USER=''
MYSQL_ROOT_PASSWORD=''


# Install and activate plugins after db connection is configured in wp-config.php
cd $WWW_ROOT && sudo -u www-data wp core install --title="$BLOG_TITLE" --admin_user="$BLOG_USER" --admin_password="$BLOG_PASSWORD" --admin_email="$BLOG_EMAIL"  --url="localhost" 
cd $WWW_ROOT && sudo -u www-data wp plugin install amazon-s3-and-cloudfront
cd $WWW_ROOT && sudo -u www-data wp plugin install amazon-web-services
cd $WWW_ROOT && sudo -u www-data wp plugin install google-analytics-for-wordpress
cd $WWW_ROOT && sudo -u www-data wp plugin install jetpack
cd $WWW_ROOT && sudo -u www-data wp plugin install nginx-helper
cd $WWW_ROOT && sudo -u www-data wp plugin install remove-category-url
cd $WWW_ROOT && sudo -u www-data wp plugin install siteurl
cd $WWW_ROOT && sudo -u www-data wp plugin install tinymce-advanced
cd $WWW_ROOT && sudo -u www-data wp plugin install wordfence
cd $WWW_ROOT && sudo -u www-data wp plugin install wordpress-importer
cd $WWW_ROOT && sudo -u www-data wp plugin install wordpress-seo
cd $WWW_ROOT && sudo -u www-data wp plugin activate --all
BLOG_TITLE=''
BLOG_USER=''
BLOG_PASSWORD=''
BLOG_EMAIL=''


# Start server
supervisord -n